services:
  postgres:
    image: postgres:18.1-alpine
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: url_shortner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0-alpine
    container_name: redis_container
    restart: unless-stopped
    command: [
      "redis-server",
      "--requirepass", "redisPassword",
      "--save", "",
      "--appendonly", "no"
    ]
    ports:
      - "127.0.0.1:6379:6379"
      -
volumes:
  postgres_data: